FROM node:18-alpine

# Đặt thư mục làm việc
WORKDIR /app

# Copy package.json vào container và cài đặt dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . /app

# Build ứng dụng
RUN npm run build

# Mở cổng 5173
EXPOSE 5173

# Chạy ứng dụng
CMD ["npm", "run", "dev", "--", "--host"]
